[package]
name = "raptors"
version = "0.1.0"
edition = "2021"
workspace = ".."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.6", features = ["serde", "v4"] }
tokio = { version = "1", features =["full"] }
